-- Flyway migration for wallet schema

CREATE TABLE account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_name VARCHAR(100) NOT NULL,
    balance NUMERIC(19,4) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    version BIGINT
);

CREATE TABLE account_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    amount NUMERIC(19,4) NOT NULL,
    balance_after NUMERIC(19,4) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    description VARCHAR(255),
    CONSTRAINT fk_account_transaction_account FOREIGN KEY (account_id) REFERENCES account(id)
);
