-- Flyway migration for idempotency support

CREATE TABLE idempotency_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(100) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    endpoint VARCHAR(100) NOT NULL,
    response_payload CLOB,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_idempotency_key UNIQUE (idempotency_key)
);
