-- Flyway migration: add audit log table

CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(100) NOT NULL,
    account_id BIGINT,
    action VARCHAR(100) NOT NULL,
    details VARCHAR(1000),
    created_at TIMESTAMP NOT NULL
);
